version: '3.8'

services:
  # Сервис для бэкенда
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rationx-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance_db
      - SPRING_DATASOURCE_USERNAME=matthewencore
      - SPRING_DATASOURCE_PASSWORD=ovedet92
      - JWT_SECRET=aVeryLongAndSecureSecretKeyForJwtTokensInTheApplication
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - rationx-network
    restart: unless-stopped

  # Сервис для фронтенда
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rationx-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - rationx-network
    restart: unless-stopped
    # Установка переменных окружения для фронтенда
    environment:
      - BACKEND_URL=http://backend:8080
      - CHOKIDAR_USEPOLLING=true
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173
      - VITE_DEV_SERVER_HMRHOST=localhost
      - VITE_DEV_SERVER_HMRPORT=5173

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: rationx-db
    environment:
      - POSTGRES_USER=matthewencore
      - POSTGRES_PASSWORD=ovedet92
      - POSTGRES_DB=finance_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rationx-network
    restart: unless-stopped

networks:
  rationx-network:
    driver: bridge

volumes:
  postgres-data:
