# Это основной файл настроек приложения.
# Здесь указываются параметры подключения к базе данных, настройки шаблонов и другие важные вещи.
# Если нужно сменить базу данных или изменить поведение приложения — делается это тут.
spring:
  jwt:
    secret: your-long-and-random-secret-key-here
  datasource:
    url: jdbc:postgresql://176.124.215.222:5432/finance_db
    password: ovedet92
    username: matthewencore
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      default_schema: finance
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    enabled: true
  application:
    name: FinanceApp
